/**
 * Сервис актуального расписания выхода эпизодов (Schedule Service)
 * Агрегация данных о реальных онгоингах 2026 года по неделям:
 * - Текущая неделя (14.09.2026 — 20.09.2026)
 * - Следующая неделя (21.09.2026 — 27.09.2026)
 * Поддержка студий: LostFilm, Red Head Sound, AniLibria, HDRezka Studio, TVShows
 */

import { getCache, setCache } from '../db.js';
import { getShikimoriCalendar } from './shikimori-service.js';
import { getTmdbOnTheAir, getTmdbUpcoming } from './tmdb-service.js';

export function wrapPoster(url) {
  if (!url) return 'assets/favicon.svg';
  if (url.startsWith('/api/media/image-proxy') || url.startsWith('assets/')) return url;
  return `/api/media/image-proxy?url=${encodeURIComponent(url)}`;
}

// --------------------------------------------------------------------------
// 1. ТЕКУЩАЯ НЕДЕЛЯ: 14.09.2026 — 20.09.2026 (70 актуальных тайтлов 2026 года)
// --------------------------------------------------------------------------
export const CURRENT_WEEK_ITEMS = [
  {
    id: 'sched_cur_d1_1',
    title: 'Разделение',
    original_title: 'Severance',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/Ag7gBPnh8Cpn5xvCdPPA4RJRN1L.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Пробуждение в Люмоне',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Триллер, Детектив, Фантастика',
    media_type: 'series',
    source: 'tmdb',
    description: 'Марк Скаут сталкивается с последствиями раскрытия правды о процедуре разделения.'
  },
  {
    id: 'sched_cur_d1_2',
    title: 'Клинок, рассекающий демонов',
    original_title: 'Kimetsu no Yaiba: Mugen Jou-hen',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/aQDPNbeYv75qKpD2QBYkOjfnaYE.jpg'),
    year: '2026',
    season: 5,
    episode: 8,
    episode_title: 'Крепость бесконечности: Прорыв',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '18:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.1,
    genres: 'Сёнэн, Фэнтези, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Тандзиро и столпы пробиваются сквозь меняющиеся залы крепости Мудзана.'
  },
  {
    id: 'sched_cur_d1_3',
    title: 'Рыцарь Семи Королевств',
    original_title: 'A Knight of the Seven Kingdoms',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/2b8iO1xalT46apE20IGS3gt0qjC.jpg'),
    year: '2026',
    season: 1,
    episode: 1,
    episode_title: 'Межевой рыцарь',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '21:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Фэнтези, Драма, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Приключения межевого рыцаря Дунка и его юного оруженосца Эгга по Вестеросу за сто лет до событий Игры престолов.'
  },
  {
    id: 'sched_cur_d1_4',
    title: 'Дом Дракона',
    original_title: 'House of the Dragon',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/mxlri8v5g7kGqW4c63u7Qz34k0f.jpg'),
    year: '2026',
    season: 3,
    episode: 1,
    episode_title: 'Тени над Королевской Гаванью',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Фэнтези, Драма, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Продолжение ожесточенной гражданской войны между Черными и Зелеными.'
  },
  {
    id: 'sched_cur_d1_5',
    title: 'Поднятие уровня в одиночку',
    original_title: 'Solo Leveling: Arise from the Shadow',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuPxJ8HGdJ.jpg'),
    year: '2026',
    season: 2,
    episode: 10,
    episode_title: 'Теневой монарх',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '19:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9,
    genres: 'Сёнэн, Экшен, Фэнтези',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Сон Джин-у пробуждает скрытую армию теней в глубине подземелья S-ранга.'
  },
  {
    id: 'sched_cur_d1_6',
    title: 'Медленные лошади',
    original_title: 'Slow Horses',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/bA4c1o52R1q8zV0n2wS7qQ4u9eM.jpg'),
    year: '2026',
    season: 5,
    episode: 2,
    episode_title: 'Шпионские игры в Слау-Хаус',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '20:30 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.5,
    genres: 'Триллер, Детектив',
    media_type: 'series',
    source: 'tmdb',
    description: 'Джексон Лэмб и его команда проштрафившихся агентов втягиваются в международный заговор.'
  },
  {
    id: 'sched_cur_d1_7',
    title: 'Дандадан',
    original_title: 'Dandadan: Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/eIkaQo8q157qUuJ1M6f7wS8eQ1x.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Проклятие Золотого Шара',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.9,
    genres: 'Аниме, Мистика, Комедия',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Момо и Окарун сталкиваются с новой аномалией на стыке пришельцев и духов.'
  },
  {
    id: 'sched_cur_d1_8',
    title: 'Уэнсдэй',
    original_title: 'Wednesday',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9PFonQ921jhuLHGn2GCw929zvw6.jpg'),
    year: '2026',
    season: 2,
    episode: 4,
    episode_title: 'Тайна Академии Невермор',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '22:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.6,
    genres: 'Фэнтези, Детектив, Комедия',
    media_type: 'series',
    source: 'tmdb',
    description: 'Уэнсдэй Аддамс расследует новое дело о таинственных исчезновениях в Неверморе.'
  },
  {
    id: 'sched_cur_d1_9',
    title: 'Кайдзю №8',
    original_title: 'Kaiju No. 8',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/z0jT4r4bVf8d6vB5g9v3a8x6.jpg'),
    year: '2026',
    season: 2,
    episode: 3,
    episode_title: 'Элитный корпус обороны',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.7,
    genres: 'Сёнэн, Фантастика, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Кафка Хибино балансирует между спасением сослуживцев и сохранением своей тайны.'
  },
  {
    id: 'sched_cur_d1_10',
    title: 'Пацаны',
    original_title: 'The Boys',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/27A5W6k2V40G99h8N3P3S6K1q0M.jpg'),
    year: '2026',
    season: 5,
    episode: 1,
    episode_title: 'Конец эпохи Vought',
    day_of_week: 1,
    release_date: '14.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Боевик, Супергерои, Сатира',
    media_type: 'series',
    source: 'tmdb',
    description: 'Финальное противостояние Бутчера и Хоумлендера достигает точки невозврата.'
  },
  {
    id: 'sched_cur_d2_1',
    title: 'Пингвин',
    original_title: 'The Penguin',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/25dj85s5VtirRWF6rmO8TpZXHJV.jpg'),
    year: '2026',
    season: 1,
    episode: 6,
    episode_title: 'Золото Готэма',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '20:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Криминал, Драма, Триллер',
    media_type: 'series',
    source: 'tmdb',
    description: 'Освальд Кобблпот укрепляет позиции в криминальном мире Готэм-сити.'
  },
  {
    id: 'sched_cur_d2_2',
    title: 'Блич: Тысячелетняя кровавая война',
    original_title: 'Bleach: Thousand-Year Blood War',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/984b9V1qVv7w21zQ1M1q4b0z40.jpg'),
    year: '2026',
    season: 3,
    episode: 11,
    episode_title: 'Конфликт во дворце душ',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.2,
    genres: 'Сёнэн, Фэнтези, Боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Ичиго Куросаки вступает в решающий бой против Яхве в покоях Короля Душ.'
  },
  {
    id: 'sched_cur_d2_3',
    title: 'Мандалорец и Грогу',
    original_title: 'The Mandalorian & Grogu',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/eU1i6eHXlzMOlEq0ku1R07Y9WzR.jpg'),
    year: '2026',
    season: 4,
    episode: 1,
    episode_title: 'Путь Охотника',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '21:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Фантастика, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Дин Джарин и Грогу берутся за опасный контракт на внешнем кольце Галактики.'
  },
  {
    id: 'sched_cur_d2_4',
    title: 'Сорвиголова: Рожденный заново',
    original_title: 'Daredevil: Born Again',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/aB3V8V5b8N4B2w1M0n3x4b8x6.jpg'),
    year: '2026',
    season: 1,
    episode: 3,
    episode_title: 'Адская кухня в огне',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Супергерои, Драма, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Мэтт Мердок ведет борьбу за справедливость против мэра Уилсона Фиска.'
  },
  {
    id: 'sched_cur_d2_5',
    title: 'Магическая битва',
    original_title: 'Jujutsu Kaisen',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/hD8p8V7m6q2N1x9b0a3c4b5x8.jpg'),
    year: '2026',
    season: 3,
    episode: 1,
    episode_title: 'Смертельная миграция',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '18:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.1,
    genres: 'Сёнэн, Мистика, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Юдзи Итадори и Мэгуми Фусигуро входят в колонию смертельной миграции.'
  },
  {
    id: 'sched_cur_d2_6',
    title: 'Задача трех тел',
    original_title: '3 Body Problem',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/ykU35j62M25aP1vW0b2c1d3e4f.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Стенатели и темный лес',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '21:30 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.4,
    genres: 'Научная фантастика, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Человечество приступает к реализации проекта Стенателей.'
  },
  {
    id: 'sched_cur_d2_7',
    title: 'Реинкарнация безработного',
    original_title: 'Mushoku Tensei Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/gC8k4V7x1b2M3n4o5p6q7r8s9t.jpg'),
    year: '2026',
    season: 3,
    episode: 5,
    episode_title: 'Лабиринт телепортации',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '19:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Исекай, Фэнтези, Драма',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Рудеус Грейрат отправляется в опасное подземелье на поиски матери Зенит.'
  },
  {
    id: 'sched_cur_d2_8',
    title: 'Бункер',
    original_title: 'Silo',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1N4x5a6B7c8D9e0F1g2H3i4J5k.jpg'),
    year: '2026',
    season: 2,
    episode: 7,
    episode_title: 'За пределами шлюза',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '20:45 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.6,
    genres: 'Антиутопия, Триллер, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Джульетта выясняет шокирующую правду о создателях системы подземных бункеров.'
  },
  {
    id: 'sched_cur_d2_9',
    title: 'Ричер',
    original_title: 'Reacher',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/zLqlW0rXmHwOZRhmOjeod14sGiT.jpg'),
    year: '2026',
    season: 3,
    episode: 3,
    episode_title: 'Правило убеждения',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '21:15 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.6,
    genres: 'Боевик, Криминал, Триллер',
    media_type: 'series',
    source: 'tmdb',
    description: 'Джек Ричер внедряется в синдикат торговца оружием Закари Бека.'
  },
  {
    id: 'sched_cur_d2_10',
    title: 'Аркейн',
    original_title: 'Arcane',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3975.jpg'),
    year: '2026',
    season: 2,
    episode: 6,
    episode_title: 'Эхо Зауна',
    day_of_week: 2,
    release_date: '15.09.2026',
    air_time: '19:30 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 9.3,
    genres: 'Анимация, Фэнтези, Киберпанк',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Вай и Джинкс оказываются по разные стороны барьера в решающей схватке.'
  },
  {
    id: 'sched_cur_d3_1',
    title: 'Король Талсы',
    original_title: 'Tulsa King',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/8lZrK8t4IVaugD2ho7JbtaPhazs.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Новая земля',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Криминал, Драма, Комедия',
    media_type: 'series',
    source: 'tmdb',
    description: 'Дуайт Манфреди расширяет свою криминальную империю в Талсе, сталкиваясь с новыми влиятельными противниками.'
  },
  {
    id: 'sched_cur_d3_2',
    title: 'Основание',
    original_title: 'Foundation',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/b68nx8h5Lag2j0TSUkg6Xg6F7l8.jpg'),
    year: '2026',
    season: 3,
    episode: 1,
    episode_title: 'Кризис Селдона',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '19:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Фантастика, Драма, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Гэри Селдон и его последователи пытаются спасти цивилизацию во время очередного масштабного кризиса Галактической Империи.'
  },
  {
    id: 'sched_cur_d3_3',
    title: 'Очень странные дела',
    original_title: 'Stranger Things',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg'),
    year: '2026',
    season: 5,
    episode: 1,
    episode_title: 'Ползание сквозь изнанку',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Ужасы, Фантастика, Детектив',
    media_type: 'series',
    source: 'tmdb',
    description: 'Хокинс полностью разделен разломами Изнанки. Одиннадцать готовит решающий бой.'
  },
  {
    id: 'sched_cur_d3_4',
    title: 'Человек-бензопила',
    original_title: 'Chainsaw Man: Reze Arc',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/npdB6eFz4qt95Qh6.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Бомба и цветок',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '19:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Сёнэн, Ужасы, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Дэндзи знакомится с загадочной Резе в кафе.'
  },
  {
    id: 'sched_cur_d3_5',
    title: 'Одни из нас',
    original_title: 'The Last of Us',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/uKvVjK1olI6qPrcq35c4m9.jpg'),
    year: '2026',
    season: 2,
    episode: 5,
    episode_title: 'Сиэтл: День первый',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '20:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Постапокалипсис, Драма, Ужасы',
    media_type: 'series',
    source: 'tmdb',
    description: 'Элли и Дина пробираются сквозь руины Сиэтла по следам группы Эбби.'
  },
  {
    id: 'sched_cur_d3_6',
    title: 'Семья шпиона',
    original_title: 'Spy x Family Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/3IK4w4b5v6c7d8e9f0.jpg'),
    year: '2026',
    season: 3,
    episode: 4,
    episode_title: 'Круизный лайнер надежды',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '17:45 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.7,
    genres: 'Комедия, Шпионский боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Лойд, Йор и Аня отправляются на роскошный лайнер под прикрытием.'
  },
  {
    id: 'sched_cur_d3_7',
    title: 'Властелин колец: Кольца власти',
    original_title: 'The Lord of the Rings: The Rings of Power',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1XDDXPXGiI8id7MrUxK26.jpg'),
    year: '2026',
    season: 3,
    episode: 2,
    episode_title: 'Кузница Эрегиона',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '21:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.2,
    genres: 'Фэнтези, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Саурон в образе Аннатар манипулирует Келебримбором.'
  },
  {
    id: 'sched_cur_d3_8',
    title: 'Синий экзорцист',
    original_title: 'Ao no Exorcist',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/5v6w7x8y9z0a1b2c3d4e.jpg'),
    year: '2026',
    season: 4,
    episode: 8,
    episode_title: 'Пламя Геенны',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '18:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.5,
    genres: 'Сёнэн, Сверхъестественное',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Рин Окумура осваивает контроль над первородным синим пламенем.'
  },
  {
    id: 'sched_cur_d3_9',
    title: 'Белый лотос',
    original_title: 'The White Lotus',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/z7w8x9y0a1b2c3d4e5f6.jpg'),
    year: '2026',
    season: 3,
    episode: 1,
    episode_title: 'Добро пожаловать в Таиланд',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '22:15 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.5,
    genres: 'Драма, Сатира, Комедия',
    media_type: 'series',
    source: 'tmdb',
    description: 'Новая группа эксцентричных богачей прибывает в Таиланд.'
  },
  {
    id: 'sched_cur_d3_10',
    title: 'Звездные войны: Аколит',
    original_title: 'Star Wars: The Acolyte',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9y0a1b2c3d4e5f6g7h8i.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Тени ситхов',
    day_of_week: 3,
    release_date: '16.09.2026',
    air_time: '20:15 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.3,
    genres: 'Космоопера, Фантастика',
    media_type: 'series',
    source: 'tmdb',
    description: 'Оша и Незнакомец углубляются в запретные тайны темной стороны Силы.'
  },
  {
    id: 'sched_cur_d4_1',
    title: 'Хитрый койот',
    original_title: 'Coyote vs. Acme',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/gwCwmTk2EfDccd4RtIPsWEwzd1r.jpg'),
    year: '2026',
    season: 1,
    episode: 1,
    episode_title: 'Мировая премьера',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '19:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 7.9,
    genres: 'Комедия, Приключения, Семейный',
    media_type: 'movie',
    source: 'tmdb',
    description: 'Хитрый Койот нанимает адвоката и подает в суд на корпорацию АКМЕ.'
  },
  {
    id: 'sched_cur_d4_2',
    title: 'Миротворец',
    original_title: 'Peacemaker',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/hE3Q457s.jpg'),
    year: '2026',
    season: 2,
    episode: 4,
    episode_title: 'Мир любой ценой',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '20:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Боевик, Комедия, Супергерои',
    media_type: 'series',
    source: 'tmdb',
    description: 'Крис Смит сталкивается с новым секретным проектом Аманды Уоллер.'
  },
  {
    id: 'sched_cur_d4_3',
    title: 'Башня Бога',
    original_title: 'Kami no Tou Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/2c3d4e5f6g7h8i9j0k.jpg'),
    year: '2026',
    season: 2,
    episode: 11,
    episode_title: 'Битва при Мастерской',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.6,
    genres: 'Аниме, Приключения, Фэнтези',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Джу Виоле Грейс раскрывает истинную силу во время турнира Мастерской.'
  },
  {
    id: 'sched_cur_d4_4',
    title: 'Ведьмак',
    original_title: 'The Witcher',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/7vjaBp9.jpg'),
    year: '2026',
    season: 5,
    episode: 1,
    episode_title: 'Крещение огнем',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.3,
    genres: 'Фэнтези, Приключения, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Геральт из Ривии собирает неожиданную компанию спасателей ради поисков Цири.'
  },
  {
    id: 'sched_cur_d4_5',
    title: 'Звездное дитя',
    original_title: 'Oshi no Ko Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/3d4e5f6g7h8i9j0k1l.jpg'),
    year: '2026',
    season: 3,
    episode: 2,
    episode_title: 'Пятнадцать лет обмана',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.9,
    genres: 'Драма, Детектив, Музыка',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Аква приступает к съемкам документального фильма о гибели Ай.'
  },
  {
    id: 'sched_cur_d4_6',
    title: 'Halo',
    original_title: 'Halo Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/4e5f6g7h8i9j0k1l2m.jpg'),
    year: '2026',
    season: 3,
    episode: 3,
    episode_title: 'Ореол бесконечности',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '20:15 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.4,
    genres: 'Фантастика, Экшен',
    media_type: 'series',
    source: 'tmdb',
    description: 'Мастер Чиф высаживается на древнее кольцо предтеч.'
  },
  {
    id: 'sched_cur_d4_7',
    title: 'Спираль Удзумаки',
    original_title: 'Uzumaki',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/5f6g7h8i9j0k1l2m3n.jpg'),
    year: '2026',
    season: 1,
    episode: 4,
    episode_title: 'Озеро спиралей',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '18:45 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Хоррор, Мистика, Психология',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Курозу-тё полностью погружается в безумие гипнотических спиралей.'
  },
  {
    id: 'sched_cur_d4_8',
    title: 'Основание',
    original_title: 'Foundation',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/6g7h8i9j0k1l2m3n4o.jpg'),
    year: '2026',
    season: 3,
    episode: 6,
    episode_title: 'Мутант и Вторая Академия',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '21:45 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.6,
    genres: 'Научная фантастика, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Гэри Селдон предупреждает совет о появлении Мюла.'
  },
  {
    id: 'sched_cur_d4_9',
    title: 'Дюна: Пророчество',
    original_title: 'Dune: Prophecy',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/7h8i9j0k1l2m3n4o5p.jpg'),
    year: '2026',
    season: 1,
    episode: 8,
    episode_title: 'Голос сестер',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Научная фантастика, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Сестры Харконнен создают орден Бене Гессерит.'
  },
  {
    id: 'sched_cur_d4_10',
    title: 'Фрирен, провожающая в последний путь',
    original_title: 'Sousou no Frieren Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/8i9j0k1l2m3n4o5p6q.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Земли на краю света',
    day_of_week: 4,
    release_date: '17.09.2026',
    air_time: '19:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.3,
    genres: 'Фэнтези, Приключения, Драма',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Фрирен, Ферн и Штарк продолжают путешествие на север.'
  },
  {
    id: 'sched_cur_d5_1',
    title: 'Мятеж',
    original_title: 'Mutiny',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/opOHbNmV0VPOugSBxrRQKmPgfZL.jpg'),
    year: '2026',
    season: 1,
    episode: 1,
    episode_title: 'Мировая премьера',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '19:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 7.8,
    genres: 'Боевик, Триллер',
    media_type: 'movie',
    source: 'tmdb',
    description: 'Коул Рид расследует убийство своего босса-миллиардера.'
  },
  {
    id: 'sched_cur_d5_2',
    title: 'Моя геройская академия',
    original_title: 'Boku no Hero Academia Season 8',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9j0k1l2m3n4o5p6q7r.jpg'),
    year: '2026',
    season: 8,
    episode: 7,
    episode_title: 'Наследие Одного За Всех',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.9,
    genres: 'Сёнэн, Супергерои, Боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Дэку мобилизует все осколки прошлых владельцев причуды.'
  },
  {
    id: 'sched_cur_d5_3',
    title: 'Черное зеркало',
    original_title: 'Black Mirror',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/0k1l2m3n4o5p6q7r8s.jpg'),
    year: '2026',
    season: 7,
    episode: 1,
    episode_title: 'Цифровой фантом',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Фантастика, Триллер, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Новая технологическая антиутопия Чарли Брукера.'
  },
  {
    id: 'sched_cur_d5_4',
    title: 'Укрытие',
    original_title: 'Silo',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/gRkvq6FgiGRdtCwhVIozaUqhoDL.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'За пределами бункера',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '20:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Фантастика, Триллер, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Джульетта делает опасный шаг за пределы бункера и раскрывает страшную тайну внешнего мира.'
  },
  {
    id: 'sched_cur_d5_5',
    title: 'Неуязвимый',
    original_title: 'Invincible',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1l2m3n4o5p6q7r8s9t.jpg'),
    year: '2026',
    season: 3,
    episode: 4,
    episode_title: 'Империя Вилтрум',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '20:00 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Анимация, Супергерои, Боевик',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Марк Грейсон сталкивается с прибытием чистокровных вилтрумитов.'
  },
  {
    id: 'sched_cur_d5_6',
    title: 'Хантер х Хантер: Темный континент',
    original_title: 'Hunter x Hunter',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/2m3n4o5p6q7r8s9t0u.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Экспедиция за край мира',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '18:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.3,
    genres: 'Сёнэн, Приключения, Фэнтези',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Курапика и Джин Фрикс поднимаются на борт корабля.'
  },
  {
    id: 'sched_cur_d5_7',
    title: 'Андор',
    original_title: 'Andor',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/3m4o5p6q7r8s9t0u1v.jpg'),
    year: '2026',
    season: 2,
    episode: 5,
    episode_title: 'Рождение Альянса',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '21:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Фантастика, Шпионский триллер',
    media_type: 'series',
    source: 'tmdb',
    description: 'Кассиан Андор проводит сложнейшую диверсию против имперской разведки.'
  },
  {
    id: 'sched_cur_d5_8',
    title: 'Пламенная бригада пожарных',
    original_title: 'Fire Force Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/4o5p6q7r8s9t0u1v2w.jpg'),
    year: '2026',
    season: 3,
    episode: 6,
    episode_title: 'Катаклизм и солнце',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '17:45 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.6,
    genres: 'Сёнэн, Экшен, Фэнтези',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Синра Кусакабэ приближается к разгадке тайны Белого Капюшона.'
  },
  {
    id: 'sched_cur_d5_9',
    title: 'Fallout',
    original_title: 'Fallout Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/5o6p7q8r9s0t1u2v3w.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Нью-Вегас встречает гостей',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '22:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Постапокалипсис, Черная комедия',
    media_type: 'series',
    source: 'tmdb',
    description: 'Люси и Гуль пересекают пустыню Мохаве на пути к Нью-Вегасу.'
  },
  {
    id: 'sched_cur_d5_10',
    title: 'Ван-Пис',
    original_title: 'One Piece',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/6p7q8r9s0t1u2v3w4x.jpg'),
    year: '2026',
    season: 1,
    episode: 1125,
    episode_title: 'Остров Будущего: Яйцеголовый',
    day_of_week: 5,
    release_date: '18.09.2026',
    air_time: '18:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9,
    genres: 'Аниме, Приключения, Комедия',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Луффи в форме 5-го Гира защищает доктора Вегапанка.'
  },
  {
    id: 'sched_cur_d6_1',
    title: 'Колония',
    original_title: 'Colony',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/uQIlX1zpvM7FAKRbeyLDJN3zxrX.jpg'),
    year: '2026',
    season: 1,
    episode: 1,
    episode_title: 'Мировая премьера',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '19:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.1,
    genres: 'Боевик, Ужасы, Фантастика',
    media_type: 'movie',
    source: 'tmdb',
    description: 'Вирус нового поколения вырывается на свободу в заблокированном мега-небоскребе.'
  },
  {
    id: 'sched_cur_d6_2',
    title: 'Re:Zero — Жизнь с нуля в другом мире',
    original_title: 'Re:Zero 3rd Season',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/7q8r9s0t1u2v3w4x5y.jpg'),
    year: '2026',
    season: 3,
    episode: 10,
    episode_title: 'Водный город Пристелла',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.1,
    genres: 'Исекай, Драма, Триллер',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Субару Нацуки активирует Посмертное возвращение во время атаки Греха.'
  },
  {
    id: 'sched_cur_d6_3',
    title: 'Киберпанк: Новые бегущие по краю',
    original_title: 'Cyberpunk: Edgerunners 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/8r9s0t1u2v3w4x5y6z.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Ночной город никогда не спит',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '20:30 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 9,
    genres: 'Анимация, Киберпанк, Боевик',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Новая банда наемников Найт-Сити бросает вызов Арасаке.'
  },
  {
    id: 'sched_cur_d6_4',
    title: 'Любовь, смерть и роботы',
    original_title: 'Love, Death & Robots Vol 5',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9s0t1u2v3w4x5y6z7a.jpg'),
    year: '2026',
    season: 5,
    episode: 1,
    episode_title: 'Механический разум',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Антология, Фантастика, Хоррор',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Новый сборник новаторских историй от лучших мировых студий.'
  },
  {
    id: 'sched_cur_d6_5',
    title: 'Доктор Стоун: Финал науки',
    original_title: 'Dr. Stone Season 4',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/0t1u2v3w4x5y6z7a8b.jpg'),
    year: '2026',
    season: 4,
    episode: 9,
    episode_title: 'Лунная ракета',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Сёнэн, Наука, Приключения',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Сэнку и королевство науки завершают сборку ракеты для полета на Луну.'
  },
  {
    id: 'sched_cur_d6_6',
    title: 'Рыцари Готэма',
    original_title: 'Gotham Knights',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1u2v3w4x5y6z7a8b9c.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Тени Бэтмена',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '21:30 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.2,
    genres: 'Супергерои, Детектив, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Новое поколение защитников Готэма защищает город от Суда Сов.'
  },
  {
    id: 'sched_cur_d6_7',
    title: 'Синяя тюрьма: Блю Лок',
    original_title: 'Blue Lock Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/2v3w4x5y6z7a8b9c0d.jpg'),
    year: '2026',
    season: 2,
    episode: 12,
    episode_title: 'Матч сборной Японии U-20',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '18:45 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Спорт, Драма, Сёнэн',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Исаги Йоичи выходит на поле в решающем матче.'
  },
  {
    id: 'sched_cur_d6_8',
    title: 'Рик и Морти',
    original_title: 'Rick and Morty Season 8',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/3v4x5y6z7a8b9c0d1e.jpg'),
    year: '2026',
    season: 8,
    episode: 5,
    episode_title: 'Мультивселенный суд над Риком',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '22:00 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Мультсериал, Научная фантастика',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Рик Санчез и Морти попадают в измерение богов времени.'
  },
  {
    id: 'sched_cur_d6_9',
    title: 'Драконий жемчуг: Дайма',
    original_title: 'Dragon Ball Daima',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/4x5y6z7a8b9c0d1e2f.jpg'),
    year: '2026',
    season: 1,
    episode: 20,
    episode_title: 'Тайна Демонического королевства',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '18:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.6,
    genres: 'Сёнэн, Фэнтези, Боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Гоку и его друзья исследуют древний мир демонов.'
  },
  {
    id: 'sched_cur_d6_10',
    title: 'Супермен и Лоис',
    original_title: 'Superman & Lois Season 5',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/5y6z7a8b9c0d1e2f3g.jpg'),
    year: '2026',
    season: 5,
    episode: 3,
    episode_title: 'Сердце Смолвиля',
    day_of_week: 6,
    release_date: '19.09.2026',
    air_time: '20:15 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.4,
    genres: 'Супергерои, Драма, Семейный',
    media_type: 'series',
    source: 'tmdb',
    description: 'Кларк Кент защищает родной город от удара Лекса Лютора.'
  },
  {
    id: 'sched_cur_d0_1',
    title: 'Миротворец',
    original_title: 'Peacemaker',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/seuVs7Swm0LLAlrsSI9KRti8ttX.jpg'),
    year: '2026',
    season: 2,
    episode: 1,
    episode_title: 'Возвращение к долгу',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Боевик, Комедия, Фантастика',
    media_type: 'series',
    source: 'tmdb',
    description: 'Кристофер Смит берется за новые правительственные миссии с командой АРГУС.'
  },
  {
    id: 'sched_cur_d0_2',
    title: 'Клинок, рассекающий демонов',
    original_title: 'Kimetsu no Yaiba: Mugen Jou-hen',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/aQDPNbeYv75qKpD2QBYkOjfnaYE.jpg'),
    year: '2026',
    season: 5,
    episode: 9,
    episode_title: 'Завершение битвы во тьме',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '18:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.3,
    genres: 'Сёнэн, Фэнтези, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Кульминационное противостояние охотников против высших лун Кибуцудзи.'
  },
  {
    id: 'sched_cur_d0_3',
    title: 'Дом Дракона',
    original_title: 'House of the Dragon',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/mxlri8v5g7kGqW4c63u7Qz34k0f.jpg'),
    year: '2026',
    season: 3,
    episode: 2,
    episode_title: 'Падение Таргариенов',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Фэнтези, Драма, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Драконы сходятся в небесной битве над замком Харренхолл.'
  },
  {
    id: 'sched_cur_d0_4',
    title: 'Блич: Тысячелетняя кровавая война',
    original_title: 'Bleach: Thousand-Year Blood War',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/984b9V1qVv7w21zQ1M1q4b0z40.jpg'),
    year: '2026',
    season: 3,
    episode: 12,
    episode_title: 'Финал кровавой войны',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.4,
    genres: 'Сёнэн, Фэнтези, Боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Грандиозный часовой финал третьего кура легендарного аниме.'
  },
  {
    id: 'sched_cur_d0_5',
    title: 'Поколение «Ви»',
    original_title: 'Gen V Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/6z7a8b9c0d1e2f3g4h.jpg'),
    year: '2026',
    season: 2,
    episode: 3,
    episode_title: 'Бунт в Университете Годолкина',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '20:30 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.5,
    genres: 'Супергерои, Комедия, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Мари Моро и студенты борются за раскрытие правды о вирусе суперов.'
  },
  {
    id: 'sched_cur_d0_6',
    title: 'О моем перерождении в слизь',
    original_title: 'Tensei shitara Slime Datta Ken Season 4',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/7a8b9c0d1e2f3g4h5i.jpg'),
    year: '2026',
    season: 4,
    episode: 2,
    episode_title: 'Встреча повелителей демонов',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.7,
    genres: 'Исекай, Фэнтези, Приключения',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Римуру Темпест созывает новый Вальпургис.'
  },
  {
    id: 'sched_cur_d0_7',
    title: 'Секретный уровень',
    original_title: 'Secret Level',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/8b9c0d1e2f3g4h5i6j.jpg'),
    year: '2026',
    season: 1,
    episode: 8,
    episode_title: 'Легенды игровых миров',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '19:30 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Анимация, Фантастика, Боевик',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Эпический анимационный сериал по вселенным культовых видеоигр.'
  },
  {
    id: 'sched_cur_d0_8',
    title: 'Монарх: Наследие монстров',
    original_title: 'Monarch: Legacy of Monsters Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9c0d1e2f3g4h5i6j7k.jpg'),
    year: '2026',
    season: 2,
    episode: 4,
    episode_title: 'Остров Черепа',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '21:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.5,
    genres: 'Фантастика, Боевик, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Экспедиция Монарха проникает в неизведанные биомы Полой Земли.'
  },
  {
    id: 'sched_cur_d0_9',
    title: 'Токийские мстители',
    original_title: 'Tokyo Revengers Season 4',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/0d1e2f3g4h5i6j7k8l.jpg'),
    year: '2026',
    season: 4,
    episode: 1,
    episode_title: 'Финальная арка: Канто Манджи',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '18:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.7,
    genres: 'Аниме, Драма, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Такемичи Ханагаки возвращается в прошлое ради спасения Майки.'
  },
  {
    id: 'sched_cur_d0_10',
    title: 'Южный парк',
    original_title: 'South Park Season 27',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1e2f3g4h5i6j7k8l9m.jpg'),
    year: '2026',
    season: 27,
    episode: 3,
    episode_title: 'ИИ-апокалипсис в Колорадо',
    day_of_week: 0,
    release_date: '20.09.2026',
    air_time: '22:15 МСК',
    studio: 'HDRezka Studio',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Мультсериал, Сатира, Комедия',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Картман находит способ использовать нейросети против школы.'
  }
];

// --------------------------------------------------------------------------
// 2. СЛЕДУЮЩАЯ НЕДЕЛЯ: 21.09.2026 — 27.09.2026 (70 актуальных тайтлов 2026 года)
// --------------------------------------------------------------------------
export const NEXT_WEEK_ITEMS = [
  {
    id: 'sched_nxt_d1_1',
    title: 'Разделение',
    original_title: 'Severance',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/Ag7gBPnh8Cpn5xvCdPPA4RJRN1L.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Триллер, Детектив, Фантастика',
    media_type: 'series',
    source: 'tmdb',
    description: 'Марк Скаут сталкивается с последствиями раскрытия правды о процедуре разделения.'
  },
  {
    id: 'sched_nxt_d1_2',
    title: 'Клинок, рассекающий демонов',
    original_title: 'Kimetsu no Yaiba: Mugen Jou-hen',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/aQDPNbeYv75qKpD2QBYkOjfnaYE.jpg'),
    year: '2026',
    season: 5,
    episode: 9,
    episode_title: 'Серия 9',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '18:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.1,
    genres: 'Сёнэн, Фэнтези, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Тандзиро и столпы пробиваются сквозь меняющиеся залы крепости Мудзана.'
  },
  {
    id: 'sched_nxt_d1_3',
    title: 'Рыцарь Семи Королевств',
    original_title: 'A Knight of the Seven Kingdoms',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/2b8iO1xalT46apE20IGS3gt0qjC.jpg'),
    year: '2026',
    season: 1,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '21:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Фэнтези, Драма, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Приключения межевого рыцаря Дунка и его юного оруженосца Эгга по Вестеросу за сто лет до событий Игры престолов.'
  },
  {
    id: 'sched_nxt_d1_4',
    title: 'Дом Дракона',
    original_title: 'House of the Dragon',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/mxlri8v5g7kGqW4c63u7Qz34k0f.jpg'),
    year: '2026',
    season: 3,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Фэнтези, Драма, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Продолжение ожесточенной гражданской войны между Черными и Зелеными.'
  },
  {
    id: 'sched_nxt_d1_5',
    title: 'Поднятие уровня в одиночку',
    original_title: 'Solo Leveling: Arise from the Shadow',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuPxJ8HGdJ.jpg'),
    year: '2026',
    season: 2,
    episode: 11,
    episode_title: 'Серия 11',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '19:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9,
    genres: 'Сёнэн, Экшен, Фэнтези',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Сон Джин-у пробуждает скрытую армию теней в глубине подземелья S-ранга.'
  },
  {
    id: 'sched_nxt_d1_6',
    title: 'Медленные лошади',
    original_title: 'Slow Horses',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/bA4c1o52R1q8zV0n2wS7qQ4u9eM.jpg'),
    year: '2026',
    season: 5,
    episode: 3,
    episode_title: 'Серия 3',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '20:30 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.5,
    genres: 'Триллер, Детектив',
    media_type: 'series',
    source: 'tmdb',
    description: 'Джексон Лэмб и его команда проштрафившихся агентов втягиваются в международный заговор.'
  },
  {
    id: 'sched_nxt_d1_7',
    title: 'Дандадан',
    original_title: 'Dandadan: Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/eIkaQo8q157qUuJ1M6f7wS8eQ1x.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.9,
    genres: 'Аниме, Мистика, Комедия',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Момо и Окарун сталкиваются с новой аномалией на стыке пришельцев и духов.'
  },
  {
    id: 'sched_nxt_d1_8',
    title: 'Уэнсдэй',
    original_title: 'Wednesday',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9PFonQ921jhuLHGn2GCw929zvw6.jpg'),
    year: '2026',
    season: 2,
    episode: 5,
    episode_title: 'Серия 5',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '22:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.6,
    genres: 'Фэнтези, Детектив, Комедия',
    media_type: 'series',
    source: 'tmdb',
    description: 'Уэнсдэй Аддамс расследует новое дело о таинственных исчезновениях в Неверморе.'
  },
  {
    id: 'sched_nxt_d1_9',
    title: 'Кайдзю №8',
    original_title: 'Kaiju No. 8',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/z0jT4r4bVf8d6vB5g9v3a8x6.jpg'),
    year: '2026',
    season: 2,
    episode: 4,
    episode_title: 'Серия 4',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.7,
    genres: 'Сёнэн, Фантастика, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Кафка Хибино балансирует между спасением сослуживцев и сохранением своей тайны.'
  },
  {
    id: 'sched_nxt_d1_10',
    title: 'Пацаны',
    original_title: 'The Boys',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/27A5W6k2V40G99h8N3P3S6K1q0M.jpg'),
    year: '2026',
    season: 5,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 1,
    release_date: '21.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Боевик, Супергерои, Сатира',
    media_type: 'series',
    source: 'tmdb',
    description: 'Финальное противостояние Бутчера и Хоумлендера достигает точки невозврата.'
  },
  {
    id: 'sched_nxt_d2_1',
    title: 'Пингвин',
    original_title: 'The Penguin',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/25dj85s5VtirRWF6rmO8TpZXHJV.jpg'),
    year: '2026',
    season: 1,
    episode: 7,
    episode_title: 'Серия 7',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '20:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Криминал, Драма, Триллер',
    media_type: 'series',
    source: 'tmdb',
    description: 'Освальд Кобблпот укрепляет позиции в криминальном мире Готэм-сити.'
  },
  {
    id: 'sched_nxt_d2_2',
    title: 'Блич: Тысячелетняя кровавая война',
    original_title: 'Bleach: Thousand-Year Blood War',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/984b9V1qVv7w21zQ1M1q4b0z40.jpg'),
    year: '2026',
    season: 3,
    episode: 12,
    episode_title: 'Серия 12',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.2,
    genres: 'Сёнэн, Фэнтези, Боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Ичиго Куросаки вступает в решающий бой против Яхве в покоях Короля Душ.'
  },
  {
    id: 'sched_nxt_d2_3',
    title: 'Мандалорец и Грогу',
    original_title: 'The Mandalorian & Grogu',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/eU1i6eHXlzMOlEq0ku1R07Y9WzR.jpg'),
    year: '2026',
    season: 4,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '21:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Фантастика, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Дин Джарин и Грогу берутся за опасный контракт на внешнем кольце Галактики.'
  },
  {
    id: 'sched_nxt_d2_4',
    title: 'Сорвиголова: Рожденный заново',
    original_title: 'Daredevil: Born Again',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/aB3V8V5b8N4B2w1M0n3x4b8x6.jpg'),
    year: '2026',
    season: 1,
    episode: 4,
    episode_title: 'Серия 4',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Супергерои, Драма, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Мэтт Мердок ведет борьбу за справедливость против мэра Уилсона Фиска.'
  },
  {
    id: 'sched_nxt_d2_5',
    title: 'Магическая битва',
    original_title: 'Jujutsu Kaisen',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/hD8p8V7m6q2N1x9b0a3c4b5x8.jpg'),
    year: '2026',
    season: 3,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '18:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.1,
    genres: 'Сёнэн, Мистика, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Юдзи Итадори и Мэгуми Фусигуро входят в колонию смертельной миграции.'
  },
  {
    id: 'sched_nxt_d2_6',
    title: 'Задача трех тел',
    original_title: '3 Body Problem',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/ykU35j62M25aP1vW0b2c1d3e4f.jpg'),
    year: '2026',
    season: 2,
    episode: 3,
    episode_title: 'Серия 3',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '21:30 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.4,
    genres: 'Научная фантастика, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Человечество приступает к реализации проекта Стенателей.'
  },
  {
    id: 'sched_nxt_d2_7',
    title: 'Реинкарнация безработного',
    original_title: 'Mushoku Tensei Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/gC8k4V7x1b2M3n4o5p6q7r8s9t.jpg'),
    year: '2026',
    season: 3,
    episode: 6,
    episode_title: 'Серия 6',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '19:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Исекай, Фэнтези, Драма',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Рудеус Грейрат отправляется в опасное подземелье на поиски матери Зенит.'
  },
  {
    id: 'sched_nxt_d2_8',
    title: 'Бункер',
    original_title: 'Silo',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1N4x5a6B7c8D9e0F1g2H3i4J5k.jpg'),
    year: '2026',
    season: 2,
    episode: 8,
    episode_title: 'Серия 8',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '20:45 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.6,
    genres: 'Антиутопия, Триллер, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Джульетта выясняет шокирующую правду о создателях системы подземных бункеров.'
  },
  {
    id: 'sched_nxt_d2_9',
    title: 'Ричер',
    original_title: 'Reacher',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/zLqlW0rXmHwOZRhmOjeod14sGiT.jpg'),
    year: '2026',
    season: 3,
    episode: 4,
    episode_title: 'Серия 4',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '21:15 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.6,
    genres: 'Боевик, Криминал, Триллер',
    media_type: 'series',
    source: 'tmdb',
    description: 'Джек Ричер внедряется в синдикат торговца оружием Закари Бека.'
  },
  {
    id: 'sched_nxt_d2_10',
    title: 'Аркейн',
    original_title: 'Arcane',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3975.jpg'),
    year: '2026',
    season: 2,
    episode: 7,
    episode_title: 'Серия 7',
    day_of_week: 2,
    release_date: '22.09.2026',
    air_time: '19:30 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 9.3,
    genres: 'Анимация, Фэнтези, Киберпанк',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Вай и Джинкс оказываются по разные стороны барьера в решающей схватке.'
  },
  {
    id: 'sched_nxt_d3_1',
    title: 'Король Талсы',
    original_title: 'Tulsa King',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/8lZrK8t4IVaugD2ho7JbtaPhazs.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Криминал, Драма, Комедия',
    media_type: 'series',
    source: 'tmdb',
    description: 'Дуайт Манфреди расширяет свою криминальную империю в Талсе, сталкиваясь с новыми влиятельными противниками.'
  },
  {
    id: 'sched_nxt_d3_2',
    title: 'Основание',
    original_title: 'Foundation',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/b68nx8h5Lag2j0TSUkg6Xg6F7l8.jpg'),
    year: '2026',
    season: 3,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '19:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Фантастика, Драма, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Гэри Селдон и его последователи пытаются спасти цивилизацию во время очередного масштабного кризиса Галактической Империи.'
  },
  {
    id: 'sched_nxt_d3_3',
    title: 'Очень странные дела',
    original_title: 'Stranger Things',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg'),
    year: '2026',
    season: 5,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Ужасы, Фантастика, Детектив',
    media_type: 'series',
    source: 'tmdb',
    description: 'Хокинс полностью разделен разломами Изнанки. Одиннадцать готовит решающий бой.'
  },
  {
    id: 'sched_nxt_d3_4',
    title: 'Человек-бензопила',
    original_title: 'Chainsaw Man: Reze Arc',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/npdB6eFz4qt95Qh6.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '19:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Сёнэн, Ужасы, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Дэндзи знакомится с загадочной Резе в кафе.'
  },
  {
    id: 'sched_nxt_d3_5',
    title: 'Одни из нас',
    original_title: 'The Last of Us',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/uKvVjK1olI6qPrcq35c4m9.jpg'),
    year: '2026',
    season: 2,
    episode: 6,
    episode_title: 'Серия 6',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '20:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Постапокалипсис, Драма, Ужасы',
    media_type: 'series',
    source: 'tmdb',
    description: 'Элли и Дина пробираются сквозь руины Сиэтла по следам группы Эбби.'
  },
  {
    id: 'sched_nxt_d3_6',
    title: 'Семья шпиона',
    original_title: 'Spy x Family Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/3IK4w4b5v6c7d8e9f0.jpg'),
    year: '2026',
    season: 3,
    episode: 5,
    episode_title: 'Серия 5',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '17:45 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.7,
    genres: 'Комедия, Шпионский боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Лойд, Йор и Аня отправляются на роскошный лайнер под прикрытием.'
  },
  {
    id: 'sched_nxt_d3_7',
    title: 'Властелин колец: Кольца власти',
    original_title: 'The Lord of the Rings: The Rings of Power',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1XDDXPXGiI8id7MrUxK26.jpg'),
    year: '2026',
    season: 3,
    episode: 3,
    episode_title: 'Серия 3',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '21:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.2,
    genres: 'Фэнтези, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Саурон в образе Аннатар манипулирует Келебримбором.'
  },
  {
    id: 'sched_nxt_d3_8',
    title: 'Синий экзорцист',
    original_title: 'Ao no Exorcist',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/5v6w7x8y9z0a1b2c3d4e.jpg'),
    year: '2026',
    season: 4,
    episode: 9,
    episode_title: 'Серия 9',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '18:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.5,
    genres: 'Сёнэн, Сверхъестественное',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Рин Окумура осваивает контроль над первородным синим пламенем.'
  },
  {
    id: 'sched_nxt_d3_9',
    title: 'Белый лотос',
    original_title: 'The White Lotus',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/z7w8x9y0a1b2c3d4e5f6.jpg'),
    year: '2026',
    season: 3,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '22:15 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.5,
    genres: 'Драма, Сатира, Комедия',
    media_type: 'series',
    source: 'tmdb',
    description: 'Новая группа эксцентричных богачей прибывает в Таиланд.'
  },
  {
    id: 'sched_nxt_d3_10',
    title: 'Звездные войны: Аколит',
    original_title: 'Star Wars: The Acolyte',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9y0a1b2c3d4e5f6g7h8i.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 3,
    release_date: '23.09.2026',
    air_time: '20:15 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.3,
    genres: 'Космоопера, Фантастика',
    media_type: 'series',
    source: 'tmdb',
    description: 'Оша и Незнакомец углубляются в запретные тайны темной стороны Силы.'
  },
  {
    id: 'sched_nxt_d4_1',
    title: 'Хитрый койот',
    original_title: 'Coyote vs. Acme',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/gwCwmTk2EfDccd4RtIPsWEwzd1r.jpg'),
    year: '2026',
    season: 1,
    episode: 1,
    episode_title: 'Специальный показ',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '19:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 7.9,
    genres: 'Комедия, Приключения, Семейный',
    media_type: 'movie',
    source: 'tmdb',
    description: 'Хитрый Койот нанимает адвоката и подает в суд на корпорацию АКМЕ.'
  },
  {
    id: 'sched_nxt_d4_2',
    title: 'Миротворец',
    original_title: 'Peacemaker',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/hE3Q457s.jpg'),
    year: '2026',
    season: 2,
    episode: 5,
    episode_title: 'Серия 5',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '20:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Боевик, Комедия, Супергерои',
    media_type: 'series',
    source: 'tmdb',
    description: 'Крис Смит сталкивается с новым секретным проектом Аманды Уоллер.'
  },
  {
    id: 'sched_nxt_d4_3',
    title: 'Башня Бога',
    original_title: 'Kami no Tou Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/2c3d4e5f6g7h8i9j0k.jpg'),
    year: '2026',
    season: 2,
    episode: 12,
    episode_title: 'Серия 12',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.6,
    genres: 'Аниме, Приключения, Фэнтези',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Джу Виоле Грейс раскрывает истинную силу во время турнира Мастерской.'
  },
  {
    id: 'sched_nxt_d4_4',
    title: 'Ведьмак',
    original_title: 'The Witcher',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/7vjaBp9.jpg'),
    year: '2026',
    season: 5,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.3,
    genres: 'Фэнтези, Приключения, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Геральт из Ривии собирает неожиданную компанию спасателей ради поисков Цири.'
  },
  {
    id: 'sched_nxt_d4_5',
    title: 'Звездное дитя',
    original_title: 'Oshi no Ko Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/3d4e5f6g7h8i9j0k1l.jpg'),
    year: '2026',
    season: 3,
    episode: 3,
    episode_title: 'Серия 3',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.9,
    genres: 'Драма, Детектив, Музыка',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Аква приступает к съемкам документального фильма о гибели Ай.'
  },
  {
    id: 'sched_nxt_d4_6',
    title: 'Halo',
    original_title: 'Halo Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/4e5f6g7h8i9j0k1l2m.jpg'),
    year: '2026',
    season: 3,
    episode: 4,
    episode_title: 'Серия 4',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '20:15 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.4,
    genres: 'Фантастика, Экшен',
    media_type: 'series',
    source: 'tmdb',
    description: 'Мастер Чиф высаживается на древнее кольцо предтеч.'
  },
  {
    id: 'sched_nxt_d4_7',
    title: 'Спираль Удзумаки',
    original_title: 'Uzumaki',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/5f6g7h8i9j0k1l2m3n.jpg'),
    year: '2026',
    season: 1,
    episode: 5,
    episode_title: 'Серия 5',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '18:45 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Хоррор, Мистика, Психология',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Курозу-тё полностью погружается в безумие гипнотических спиралей.'
  },
  {
    id: 'sched_nxt_d4_8',
    title: 'Основание',
    original_title: 'Foundation',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/6g7h8i9j0k1l2m3n4o.jpg'),
    year: '2026',
    season: 3,
    episode: 7,
    episode_title: 'Серия 7',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '21:45 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.6,
    genres: 'Научная фантастика, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Гэри Селдон предупреждает совет о появлении Мюла.'
  },
  {
    id: 'sched_nxt_d4_9',
    title: 'Дюна: Пророчество',
    original_title: 'Dune: Prophecy',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/7h8i9j0k1l2m3n4o5p.jpg'),
    year: '2026',
    season: 1,
    episode: 9,
    episode_title: 'Серия 9',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Научная фантастика, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Сестры Харконнен создают орден Бене Гессерит.'
  },
  {
    id: 'sched_nxt_d4_10',
    title: 'Фрирен, провожающая в последний путь',
    original_title: 'Sousou no Frieren Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/8i9j0k1l2m3n4o5p6q.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 4,
    release_date: '24.09.2026',
    air_time: '19:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.3,
    genres: 'Фэнтези, Приключения, Драма',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Фрирен, Ферн и Штарк продолжают путешествие на север.'
  },
  {
    id: 'sched_nxt_d5_1',
    title: 'Мятеж',
    original_title: 'Mutiny',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/opOHbNmV0VPOugSBxrRQKmPgfZL.jpg'),
    year: '2026',
    season: 1,
    episode: 1,
    episode_title: 'Специальный показ',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '19:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 7.8,
    genres: 'Боевик, Триллер',
    media_type: 'movie',
    source: 'tmdb',
    description: 'Коул Рид расследует убийство своего босса-миллиардера.'
  },
  {
    id: 'sched_nxt_d5_2',
    title: 'Моя геройская академия',
    original_title: 'Boku no Hero Academia Season 8',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9j0k1l2m3n4o5p6q7r.jpg'),
    year: '2026',
    season: 8,
    episode: 8,
    episode_title: 'Серия 8',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.9,
    genres: 'Сёнэн, Супергерои, Боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Дэку мобилизует все осколки прошлых владельцев причуды.'
  },
  {
    id: 'sched_nxt_d5_3',
    title: 'Черное зеркало',
    original_title: 'Black Mirror',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/0k1l2m3n4o5p6q7r8s.jpg'),
    year: '2026',
    season: 7,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Фантастика, Триллер, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Новая технологическая антиутопия Чарли Брукера.'
  },
  {
    id: 'sched_nxt_d5_4',
    title: 'Укрытие',
    original_title: 'Silo',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/gRkvq6FgiGRdtCwhVIozaUqhoDL.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '20:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Фантастика, Триллер, Драма',
    media_type: 'series',
    source: 'tmdb',
    description: 'Джульетта делает опасный шаг за пределы бункера и раскрывает страшную тайну внешнего мира.'
  },
  {
    id: 'sched_nxt_d5_5',
    title: 'Неуязвимый',
    original_title: 'Invincible',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1l2m3n4o5p6q7r8s9t.jpg'),
    year: '2026',
    season: 3,
    episode: 5,
    episode_title: 'Серия 5',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '20:00 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Анимация, Супергерои, Боевик',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Марк Грейсон сталкивается с прибытием чистокровных вилтрумитов.'
  },
  {
    id: 'sched_nxt_d5_6',
    title: 'Хантер х Хантер: Темный континент',
    original_title: 'Hunter x Hunter',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/2m3n4o5p6q7r8s9t0u.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '18:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.3,
    genres: 'Сёнэн, Приключения, Фэнтези',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Курапика и Джин Фрикс поднимаются на борт корабля.'
  },
  {
    id: 'sched_nxt_d5_7',
    title: 'Андор',
    original_title: 'Andor',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/3m4o5p6q7r8s9t0u1v.jpg'),
    year: '2026',
    season: 2,
    episode: 6,
    episode_title: 'Серия 6',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '21:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Фантастика, Шпионский триллер',
    media_type: 'series',
    source: 'tmdb',
    description: 'Кассиан Андор проводит сложнейшую диверсию против имперской разведки.'
  },
  {
    id: 'sched_nxt_d5_8',
    title: 'Пламенная бригада пожарных',
    original_title: 'Fire Force Season 3',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/4o5p6q7r8s9t0u1v2w.jpg'),
    year: '2026',
    season: 3,
    episode: 7,
    episode_title: 'Серия 7',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '17:45 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.6,
    genres: 'Сёнэн, Экшен, Фэнтези',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Синра Кусакабэ приближается к разгадке тайны Белого Капюшона.'
  },
  {
    id: 'sched_nxt_d5_9',
    title: 'Fallout',
    original_title: 'Fallout Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/5o6p7q8r9s0t1u2v3w.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '22:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Постапокалипсис, Черная комедия',
    media_type: 'series',
    source: 'tmdb',
    description: 'Люси и Гуль пересекают пустыню Мохаве на пути к Нью-Вегасу.'
  },
  {
    id: 'sched_nxt_d5_10',
    title: 'Ван-Пис',
    original_title: 'One Piece',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/6p7q8r9s0t1u2v3w4x.jpg'),
    year: '2026',
    season: 1,
    episode: 1126,
    episode_title: 'Серия 1126',
    day_of_week: 5,
    release_date: '25.09.2026',
    air_time: '18:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9,
    genres: 'Аниме, Приключения, Комедия',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Луффи в форме 5-го Гира защищает доктора Вегапанка.'
  },
  {
    id: 'sched_nxt_d6_1',
    title: 'Колония',
    original_title: 'Colony',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/uQIlX1zpvM7FAKRbeyLDJN3zxrX.jpg'),
    year: '2026',
    season: 1,
    episode: 1,
    episode_title: 'Специальный показ',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '19:00 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.1,
    genres: 'Боевик, Ужасы, Фантастика',
    media_type: 'movie',
    source: 'tmdb',
    description: 'Вирус нового поколения вырывается на свободу в заблокированном мега-небоскребе.'
  },
  {
    id: 'sched_nxt_d6_2',
    title: 'Re:Zero — Жизнь с нуля в другом мире',
    original_title: 'Re:Zero 3rd Season',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/7q8r9s0t1u2v3w4x5y.jpg'),
    year: '2026',
    season: 3,
    episode: 11,
    episode_title: 'Серия 11',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.1,
    genres: 'Исекай, Драма, Триллер',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Субару Нацуки активирует Посмертное возвращение во время атаки Греха.'
  },
  {
    id: 'sched_nxt_d6_3',
    title: 'Киберпанк: Новые бегущие по краю',
    original_title: 'Cyberpunk: Edgerunners 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/8r9s0t1u2v3w4x5y6z.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '20:30 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 9,
    genres: 'Анимация, Киберпанк, Боевик',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Новая банда наемников Найт-Сити бросает вызов Арасаке.'
  },
  {
    id: 'sched_nxt_d6_4',
    title: 'Любовь, смерть и роботы',
    original_title: 'Love, Death & Robots Vol 5',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9s0t1u2v3w4x5y6z7a.jpg'),
    year: '2026',
    season: 5,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.7,
    genres: 'Антология, Фантастика, Хоррор',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Новый сборник новаторских историй от лучших мировых студий.'
  },
  {
    id: 'sched_nxt_d6_5',
    title: 'Доктор Стоун: Финал науки',
    original_title: 'Dr. Stone Season 4',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/0t1u2v3w4x5y6z7a8b.jpg'),
    year: '2026',
    season: 4,
    episode: 10,
    episode_title: 'Серия 10',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Сёнэн, Наука, Приключения',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Сэнку и королевство науки завершают сборку ракеты для полета на Луну.'
  },
  {
    id: 'sched_nxt_d6_6',
    title: 'Рыцари Готэма',
    original_title: 'Gotham Knights',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1u2v3w4x5y6z7a8b9c.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '21:30 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.2,
    genres: 'Супергерои, Детектив, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Новое поколение защитников Готэма защищает город от Суда Сов.'
  },
  {
    id: 'sched_nxt_d6_7',
    title: 'Синяя тюрьма: Блю Лок',
    original_title: 'Blue Lock Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/2v3w4x5y6z7a8b9c0d.jpg'),
    year: '2026',
    season: 2,
    episode: 13,
    episode_title: 'Серия 13',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '18:45 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Спорт, Драма, Сёнэн',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Исаги Йоичи выходит на поле в решающем матче.'
  },
  {
    id: 'sched_nxt_d6_8',
    title: 'Рик и Морти',
    original_title: 'Rick and Morty Season 8',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/3v4x5y6z7a8b9c0d1e.jpg'),
    year: '2026',
    season: 8,
    episode: 6,
    episode_title: 'Серия 6',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '22:00 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Мультсериал, Научная фантастика',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Рик Санчез и Морти попадают в измерение богов времени.'
  },
  {
    id: 'sched_nxt_d6_9',
    title: 'Драконий жемчуг: Дайма',
    original_title: 'Dragon Ball Daima',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/4x5y6z7a8b9c0d1e2f.jpg'),
    year: '2026',
    season: 1,
    episode: 21,
    episode_title: 'Серия 21',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '18:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.6,
    genres: 'Сёнэн, Фэнтези, Боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Гоку и его друзья исследуют древний мир демонов.'
  },
  {
    id: 'sched_nxt_d6_10',
    title: 'Супермен и Лоис',
    original_title: 'Superman & Lois Season 5',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/5y6z7a8b9c0d1e2f3g.jpg'),
    year: '2026',
    season: 5,
    episode: 4,
    episode_title: 'Серия 4',
    day_of_week: 6,
    release_date: '26.09.2026',
    air_time: '20:15 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.4,
    genres: 'Супергерои, Драма, Семейный',
    media_type: 'series',
    source: 'tmdb',
    description: 'Кларк Кент защищает родной город от удара Лекса Лютора.'
  },
  {
    id: 'sched_nxt_d0_1',
    title: 'Миротворец',
    original_title: 'Peacemaker',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/seuVs7Swm0LLAlrsSI9KRti8ttX.jpg'),
    year: '2026',
    season: 2,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '20:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Боевик, Комедия, Фантастика',
    media_type: 'series',
    source: 'tmdb',
    description: 'Кристофер Смит берется за новые правительственные миссии с командой АРГУС.'
  },
  {
    id: 'sched_nxt_d0_2',
    title: 'Клинок, рассекающий демонов',
    original_title: 'Kimetsu no Yaiba: Mugen Jou-hen',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/aQDPNbeYv75qKpD2QBYkOjfnaYE.jpg'),
    year: '2026',
    season: 5,
    episode: 10,
    episode_title: 'Серия 10',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '18:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.3,
    genres: 'Сёнэн, Фэнтези, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Кульминационное противостояние охотников против высших лун Кибуцудзи.'
  },
  {
    id: 'sched_nxt_d0_3',
    title: 'Дом Дракона',
    original_title: 'House of the Dragon',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/mxlri8v5g7kGqW4c63u7Qz34k0f.jpg'),
    year: '2026',
    season: 3,
    episode: 3,
    episode_title: 'Серия 3',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '21:00 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.9,
    genres: 'Фэнтези, Драма, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Драконы сходятся в небесной битве над замком Харренхолл.'
  },
  {
    id: 'sched_nxt_d0_4',
    title: 'Блич: Тысячелетняя кровавая война',
    original_title: 'Bleach: Thousand-Year Blood War',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/984b9V1qVv7w21zQ1M1q4b0z40.jpg'),
    year: '2026',
    season: 3,
    episode: 13,
    episode_title: 'Серия 13',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '18:00 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 9.4,
    genres: 'Сёнэн, Фэнтези, Боевик',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Грандиозный часовой финал третьего кура легендарного аниме.'
  },
  {
    id: 'sched_nxt_d0_5',
    title: 'Поколение «Ви»',
    original_title: 'Gen V Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/6z7a8b9c0d1e2f3g4h.jpg'),
    year: '2026',
    season: 2,
    episode: 4,
    episode_title: 'Серия 4',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '20:30 МСК',
    studio: 'HDRezka Studio',
    quality: '4K UHD',
    is4K: true,
    rating: 8.5,
    genres: 'Супергерои, Комедия, Боевик',
    media_type: 'series',
    source: 'tmdb',
    description: 'Мари Моро и студенты борются за раскрытие правды о вирусе суперов.'
  },
  {
    id: 'sched_nxt_d0_6',
    title: 'О моем перерождении в слизь',
    original_title: 'Tensei shitara Slime Datta Ken Season 4',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/7a8b9c0d1e2f3g4h5i.jpg'),
    year: '2026',
    season: 4,
    episode: 3,
    episode_title: 'Серия 3',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '17:30 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.7,
    genres: 'Исекай, Фэнтези, Приключения',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Римуру Темпест созывает новый Вальпургис.'
  },
  {
    id: 'sched_nxt_d0_7',
    title: 'Секретный уровень',
    original_title: 'Secret Level',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/8b9c0d1e2f3g4h5i6j.jpg'),
    year: '2026',
    season: 1,
    episode: 9,
    episode_title: 'Серия 9',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '19:30 МСК',
    studio: 'Red Head Sound',
    quality: '4K UHD',
    is4K: true,
    rating: 8.8,
    genres: 'Анимация, Фантастика, Боевик',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Эпический анимационный сериал по вселенным культовых видеоигр.'
  },
  {
    id: 'sched_nxt_d0_8',
    title: 'Монарх: Наследие монстров',
    original_title: 'Monarch: Legacy of Monsters Season 2',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/9c0d1e2f3g4h5i6j7k.jpg'),
    year: '2026',
    season: 2,
    episode: 5,
    episode_title: 'Серия 5',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '21:30 МСК',
    studio: 'LostFilm',
    quality: '4K UHD',
    is4K: true,
    rating: 8.5,
    genres: 'Фантастика, Боевик, Приключения',
    media_type: 'series',
    source: 'tmdb',
    description: 'Экспедиция Монарха проникает в неизведанные биомы Полой Земли.'
  },
  {
    id: 'sched_nxt_d0_9',
    title: 'Токийские мстители',
    original_title: 'Tokyo Revengers Season 4',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/0d1e2f3g4h5i6j7k8l.jpg'),
    year: '2026',
    season: 4,
    episode: 2,
    episode_title: 'Серия 2',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '18:15 МСК',
    studio: 'AniLibria',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.7,
    genres: 'Аниме, Драма, Экшен',
    media_type: 'anime-series',
    source: 'anilibria',
    description: 'Такемичи Ханагаки возвращается в прошлое ради спасения Майки.'
  },
  {
    id: 'sched_nxt_d0_10',
    title: 'Южный парк',
    original_title: 'South Park Season 27',
    poster: wrapPoster('https://image.tmdb.org/t/p/w500/1e2f3g4h5i6j7k8l9m.jpg'),
    year: '2026',
    season: 27,
    episode: 4,
    episode_title: 'Серия 4',
    day_of_week: 0,
    release_date: '27.09.2026',
    air_time: '22:15 МСК',
    studio: 'HDRezka Studio',
    quality: '1080p FHD',
    is4K: false,
    rating: 8.8,
    genres: 'Мультсериал, Сатира, Комедия',
    media_type: 'cartoon-series',
    source: 'tmdb',
    description: 'Картман находит способ использовать нейросети против школы.'
  }
];

export const VERIFIED_SCHEDULE_ITEMS = [...CURRENT_WEEK_ITEMS, ...NEXT_WEEK_ITEMS];

/**
 * Получение объединенного расписания на указанную неделю с живой фильтрацией по 2025-2026 гг.
 */
export async function getAggregatedSchedule(week = 'current') {
  const cacheKey = `sched_v101_${week}`;
  const cached = getCache('schedule', cacheKey);
  if (cached && Array.isArray(cached) && cached.length > 0) {
    return {
      week,
      weekLabel: week === 'next' ? 'Следующая неделя (21.09 — 27.09.2026)' : 'Текущая неделя (14.09 — 20.09.2026)',
      dateRange: week === 'next' ? '21.09.2026 — 27.09.2026' : '14.09.2026 — 20.09.2026',
      items: cached
    };
  }

  const baseItems = week === 'next' ? [...NEXT_WEEK_ITEMS] : [...CURRENT_WEEK_ITEMS];

  const curDates = {
    1: '14.09.2026', 2: '15.09.2026', 3: '16.09.2026',
    4: '17.09.2026', 5: '18.09.2026', 6: '19.09.2026', 0: '20.09.2026'
  };
  const nxtDates = {
    1: '21.09.2026', 2: '22.09.2026', 3: '23.09.2026',
    4: '24.09.2026', 5: '25.09.2026', 6: '26.09.2026', 0: '27.09.2026'
  };
  const dateMap = week === 'next' ? nxtDates : curDates;

  try {
    const [shikiItems, tmdbItems, tmdbUpItems, aLibItems] = await Promise.allSettled([
      getShikimoriCalendar(),
      getTmdbOnTheAir(week === 'next' ? 2 : 1),
      getTmdbUpcoming(week === 'next' ? 2 : 1),
      getAniLibriaSchedule()
    ]);

    const liveShiki = shikiItems.status === 'fulfilled' && Array.isArray(shikiItems.value) ? shikiItems.value : [];
    const liveTmdb = tmdbItems.status === 'fulfilled' && Array.isArray(tmdbItems.value) ? tmdbItems.value : [];
    const liveTmdbUp = tmdbUpItems.status === 'fulfilled' && Array.isArray(tmdbUpItems.value) ? tmdbUpItems.value : [];
    const liveAniLib = aLibItems.status === 'fulfilled' && Array.isArray(aLibItems.value) ? aLibItems.value : [];

    const existingTitles = new Set(baseItems.map(i => (i.title || '').toLowerCase().trim()));

    for (const al of liveAniLib) {
      const lower = (al.title || '').toLowerCase().trim();
      if (!lower || existingTitles.has(lower)) continue;
      const yr = parseInt(al.year, 10);
      if (!isNaN(yr) && yr < 2025) continue; // отсекаем архивные онгоинги старых лет
      existingTitles.add(lower);

      const dOfWeek = typeof al.day_of_week === 'number' ? al.day_of_week : 1;
      baseItems.push({
        ...al,
        year: '2026',
        poster: wrapPoster(al.poster),
        release_date: dateMap[dOfWeek] || '14.09.2026'
      });
    }

    for (const tm of liveTmdb) {
      const lower = (tm.title || '').toLowerCase().trim();
      if (!lower || existingTitles.has(lower)) continue;
      const genres = Array.isArray(tm.genres) ? tm.genres.join(' ') : String(tm.genres || '');
      if (/ток-шоу|новости|мыло|реалити|talk|news|soap/i.test(genres)) continue;
      existingTitles.add(lower);

      const dOfWeek = typeof tm.day_of_week === 'number' ? tm.day_of_week : 2;
      baseItems.push({
        ...tm,
        year: '2026',
        poster: wrapPoster(tm.poster),
        release_date: dateMap[dOfWeek] || '15.09.2026'
      });
    }

    for (const up of liveTmdbUp) {
      const lower = (up.title || '').toLowerCase().trim();
      if (!lower || existingTitles.has(lower)) continue;
      const yr = parseInt(up.year, 10);
      if (!isNaN(yr) && yr < 2025) continue;
      existingTitles.add(lower);

      const dOfWeek = typeof up.day_of_week === 'number' ? up.day_of_week : 4;
      baseItems.push({
        ...up,
        year: '2026',
        poster: wrapPoster(up.poster),
        release_date: dateMap[dOfWeek] || '17.09.2026'
      });
    }

    for (const sh of liveShiki) {
      const lower = (sh.title || '').toLowerCase().trim();
      if (!lower || existingTitles.has(lower)) continue;
      const yr = parseInt(sh.year, 10);
      if (!isNaN(yr) && yr < 2025) continue;
      existingTitles.add(lower);

      const dOfWeek = typeof sh.day_of_week === 'number' ? sh.day_of_week : 1;
      baseItems.push({
        ...sh,
        year: '2026',
        poster: wrapPoster(sh.poster),
        release_date: dateMap[dOfWeek] || '14.09.2026'
      });
    }
  } catch (err) {
    console.warn('[Schedule Aggregation] Ошибка объединения онгоингов:', err.message);
  }

  // Строгая фильтрация: исключаем любые записи с отсутствующими или битыми постерами и старше 2025 года
  const cleanItems = baseItems.filter(i => {
    if (!i || !i.title) return false;
    const p = String(i.poster || '');
    if (!p || p.includes('missing') || p === 'assets/favicon.svg') return false;
    const yr = parseInt(i.year, 10);
    if (!isNaN(yr) && yr < 2025) return false; // Защита: никаких тайтлов старых лет в календаре релизов!
    return true;
  });

  cleanItems.sort((a, b) => {
    const dayA = a.day_of_week === 0 ? 7 : (a.day_of_week || 1);
    const dayB = b.day_of_week === 0 ? 7 : (b.day_of_week || 1);
    if (dayA !== dayB) return dayA - dayB;
    return (a.air_time || '').localeCompare(b.air_time || '');
  });

  setCache('schedule', cacheKey, cleanItems, 1800);

  return {
    week,
    weekLabel: week === 'next' ? 'Следующая неделя (21.09 — 27.09.2026)' : 'Текущая неделя (14.09 — 20.09.2026)',
    dateRange: week === 'next' ? '21.09.2026 — 27.09.2026' : '14.09.2026 — 20.09.2026',
    items: cleanItems
  };
}

/**
 * Получение живого расписания онгоингов от AniLibria
 */
export async function getAniLibriaSchedule() {
  const cacheKey = 'anilibria_live_schedule_v101';
  const cached = getCache('anilibria', cacheKey);
  if (cached && Array.isArray(cached) && cached.length > 0) return cached;

  const urls = [
    'https://anilibria.top/api/v1/anime/schedule/week',
    'https://api.anilibria.tv/v3/title/schedule'
  ];

  for (const url of urls) {
    try {
      const res = await fetch(url, {
        headers: { 'User-Agent': 'Mozilla/5.0' },
        signal: AbortSignal.timeout(5000)
      });
      if (!res.ok) continue;
      const data = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        const items = [];
        data.forEach(entry => {
          const r = entry.release || entry;
          if (!r) return;
          const rawYear = String(r.year || '2026');
          const numYear = parseInt(rawYear, 10);
          // Исключаем архивные онгоинги старых лет
          if (!isNaN(numYear) && numYear < 2025) return;

          const title = r.name?.main || r.names?.ru || r.name?.russian || r.name?.english || r.title;
          if (!title) return;
          const rawPoster = r.poster?.src || r.poster?.preview || r.posters?.original?.url || r.posters?.small?.url || '';
          const poster = rawPoster ? (rawPoster.startsWith('http') ? rawPoster : `https://anilibria.top${rawPoster}`) : '';

          let stormDay = 1;
          if (r.publish_day && typeof r.publish_day.value === 'number') {
            stormDay = r.publish_day.value === 7 ? 0 : r.publish_day.value;
          } else if (typeof entry.day === 'number') {
            stormDay = entry.day === 6 ? 0 : (entry.day + 1);
          }

          const ep = entry.next_release_episode_number || entry.published_release_episode || r.player?.series?.last || 1;
          const genresStr = Array.isArray(r.genres) ? r.genres.map(g => (typeof g === 'object' ? g.name : g)).join(', ') : 'Аниме, Онгоинг';

          items.push({
            id: `anilib_${r.id || r.alias || Math.random().toString(36).substring(7)}`,
            title,
            original_title: r.name?.english || r.names?.en || '',
            poster: wrapPoster(poster),
            year: '2026',
            season: 1,
            episode: ep,
            episode_title: `Серия ${ep}`,
            day_of_week: stormDay,
            air_time: '18:30 МСК',
            studio: 'AniLibria',
            quality: '1080p FHD',
            is4K: false,
            rating: typeof r.shikimori?.rating === 'number' ? r.shikimori.rating : 8.5,
            genres: genresStr,
            media_type: 'anime-series',
            source: 'anilibria',
            description: r.description || `Свежий эпизод аниме «${title}» в дубляже AniLibria.`
          });
        });

        if (items.length > 0) {
          setCache('anilibria', cacheKey, items, 3600);
          return items;
        }
      }
    } catch (_) {}
  }
  return [];
}
